# Generated by Django 4.0.4 on 2022-07-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_percent',
            field=models.IntegerField(),
        ),
    ]
