# Generated by Django 4.0.4 on 2022-07-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Course_Name',
            new_name='course_Name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='School_Name',
            new_name='school_Name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='date',
        ),
        migrations.AddField(
            model_name='education',
            name='duration',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
