# Generated by Django 4.0.4 on 2022-07-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_course_name_education_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=300)),
                ('customerProfession', models.CharField(max_length=300)),
                ('customerComment', models.TextField()),
                ('customerImage', models.ImageField(upload_to='TestimonialsImg/')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
