# Generated by Django 4.0.4 on 2022-07-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_service_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='customerImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
